Repository rodrigoparente/al-labelling-interface, pull requests merged in 2022-10, with the labels that each got.

#25 initialize project structure and readme
  LICENSE
  README.md
  app/backend/.flake8
  app/backend/.gitignore
  app/backend/.pre-commit-config.yaml
  app/backend/pyproject.toml
  app/backend/requirements.txt
  app/docker-compose.yml
  app/frontend/.gitignore
  makefile
Labels: hacktoberfest-accepted

#27 Feature init fastapi
  .flake8
  .gitignore
  .pre-commit-config.yaml
  app/backend/.env.example
  app/backend/.gitignore
  app/backend/__init__.py
  app/backend/main.py
  app/backend/requirements.txt
  app/backend/requirements/common.txt
  app/backend/requirements/dev.txt
  app/backend/requirements/prod.txt
  app/backend/settings.py
  app/docker-compose.yml
  makefile
  pyproject.toml
Labels: hacktoberfest-accepted, backend

#28 Create backend Dockerfile
  app/backend/.dockerignore
  app/backend/Dockerfile
  app/backend/requirements/prod.txt
Labels: hacktoberfest-accepted, devops

#29 Create frontend Dockerfile
  app/frontend/.dockerignore
  app/frontend/Dockerfile
  app/frontend/nginx/default.conf
  app/frontend/src/components/Button.tsx
Labels: hacktoberfest-accepted, devops

#30 Add dev compose
  .gitignore
  app/docker-compose.yml
  app/templates/.env.dev.example
  makefile
Labels: hacktoberfest-accepted, devops

#31 18 17 create production deployment files
  README.md
  app/templates/.env.prd.backend.example
  app/templates/.env.prd.db.example
  app/templates/.env.prd.example
  app/templates/docker-compose.prd.yml
Labels: hacktoberfest-accepted, devops

#34 fixing bind configuration
  app/docker-compose.yml
  app/templates/.env.dev.example
Labels: hacktoberfest-accepted

#33 Add user model
  app/backend/accounts/models.py
Labels: hacktoberfest-accepted

#35 Add create user endpoint
  app/backend/accounts/__init__.py
  app/backend/accounts/dependencies.py
  app/backend/accounts/forms.py
  app/backend/accounts/routers.py
  app/backend/main.py
Labels: hacktoberfest-accepted

#36 Added Instance Model
  app/backend/active_model/__init__.py
  app/backend/active_model/models.py
  app/backend/active_model/utils.py
Labels: hacktoberfest-accepted

#37 Feature oauth2
  app/backend/.env.example
  app/backend/accounts/dependencies.py
  app/backend/accounts/models.py
  app/backend/accounts/routers.py
  app/backend/alli/__init__.py
  app/backend/alli/settings.py
  app/backend/main.py
  app/docker-compose.yml
  makefile
Labels: feature, hacktoberfest-accepted

#39 added active learning model
  app/backend/active_model/models.py
Labels: hacktoberfest-accepted

#40 added endpoint to upload new instances csv
  app/backend/active_model/models.py
  app/backend/active_model/routes.py
  app/backend/main.py
  app/backend/requirements/common.txt
Labels: hacktoberfest-accepted

#42 Add mongo-express
  app/backend/.env.example
  app/docker-compose.yml
  app/templates/.env.dev.example
Labels: hacktoberfest-accepted, devops

#43 login screen
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/sdk/Service.ts
  app/frontend/sdk/utils/generateQueryString.ts
  app/frontend/src/app/features/LoginForm.tsx
  app/frontend/src/app/layouts/LoggedIn.tsx
  app/frontend/src/app/layouts/LoggedOff.tsx
  app/frontend/src/app/views/Login.view.tsx
  app/frontend/src/app/views/Welcome.view.tsx
  app/frontend/src/assets/react.svg
  app/frontend/store/index.ts
  app/frontend/store/login.slice.ts
Labels: hacktoberfest-accepted, frontend

#44 registration screen
  app/frontend/src/app/assets/react.svg
  app/frontend/src/app/features/RegistrationForm.tsx
  app/frontend/src/app/index.tsx
  app/frontend/src/app/views/Registration.view.tsx
  app/frontend/src/main.tsx
Labels: hacktoberfest-accepted, frontend

#45 11 welcome screen
  app/frontend/src/app/views/Welcome.view.tsx
Labels: feature, hacktoberfest-accepted
